services:
  - type: web
    name: quick-backend
    env: node
    plan: free
    region: oregon
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Ifunnaya123@db.vcymhdqlndyanklyukka.supabase.co:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        value: ''
      - key: TWILIO_AUTH_TOKEN
        value: ''
      - key: TWILIO_PHONE_NUMBER
        value: ''
      - key: MAIL_HOST
        value: 'mail.myshop24.ng'
      - key: MAIL_PORT
        value: '465'
      - key: MAIL_USERNAME
        value: 'shop24@myshop24.ng'
      - key: MAIL_PASSWORD
        value: 'shop24123..'
      - key: MAIL_FROM_ADDRESS
        value: 'shop24@myshop24.ng'
      - key: MAIL_FROM_NAME
        value: 'QuickDrop'
